### ISSUE TITLE
Specify URL in Campaign

### ISSUE THREAD

**Issue by jordan-wright** [jordan-wright/gophish#32]
I've been originally just using an IP address as the URL template variable in campaigns, but this should be configurable per-campaign.

It will be up to the user to ensure that the URL is reachable and points to the phish admin listener (the ability to send a test email will help with this!)

**Comment by andy11** [comment]
I may be missing something, but I'm not sure if the current docs describe how this can be done.

From https://getgophish.com/documentation/Gophish%20User%20Guide.pdf:

> Next, we need to set the URL that the users will be directed to. This need to be the IP address of the gophish host (and port!) that is reachable by the users. This means that if you are only targeting internal users, you would probably be fine using the host’s internal IP address. However, if your targets are coming in externally, you will need to setup gophish to be reachable externally and set this field to be the external (public) IP address

Am I right in thinking that the gophish host that will track clicks & serve the landing page is the same server as the admin console (except on port 80)? I get 404s and am not sure the {{.URL}} template variable is working for the specific campaign & landing page. 

Is there something I need to do in addition to the steps shown in the User Guide?

Let me know if you'd like any other info. This is an awesome framework!

**Comment by jordan-wright** [comment]
Yes, the web server is on the same host as the admin console, and is listening on :80 by default.

This deals with how gophish serves landing pages to users. If no "rid" param is given, we return a 404. Otherwise, we obtain the landing page that was specified in the campaign options and serve that.

The {{.URL}} parameter automatically adds the rid param for you, so the link is clickable and will serve up the landing page.

I hope that helps! Let me know if you run into any other issues.

**Comment by andy11** [comment]
> The {{.URL}} parameter automatically adds the rid param for you, so the link is clickable and will serve up the landing page.

Hmm, in my case this doesn't seem to be happening.

In the campaign-creation menu, I have the URL field filled out with http://HOSTNAME, where HOSTNAME is the name of the machine where the gophish executable is running.

The HTML used in my template is:
`<p>To place another order, please&nbsp;<a href="{{.URL}}">click here</a>.</p>`

However the text "click here" doesn't have any RID information.

Is there any other info that would help with debugging?

**Comment by jordan-wright** [comment]
Hmmm. That's interesting. Does the click here have the host name you specified?

**Comment by andy11** [comment]
Yep it matches exactly what I put in the URL field on the campaign-creation menu. There's no "?rid=XXX" or anything else tagged onto the end.

**Comment by jordan-wright** [comment]
And, just to check, you're actually launching a campaign, right? Not just sending a test email?

**Comment by andy11** [comment]
Ah, that was it. I was just doing a test email. When I launch the campaign the RID parameter is there. 

Thanks!

**Comment by n838901** [comment]
Is there a way to hard-code the listener URL in the campaign, or could we add the ability to have a dropdown to select from?

**Comment by Blackbear710** [comment]
I'm having issues capturing data. Not sure I understand the URL for Listening Server of Gophish 

Whenever I upload ip where go phish is located (VM Linux Box)     I get an error
