### ISSUE TITLE
Site Clone

### ISSUE THREAD

**Issue by jordan-wright** [jordan-wright/gophish#4]
When creating a landing page, I'd like the ability to clone a site automatically. This would be an endpoint that takes in a URL and returns the HTML for the page. This would be put in the ```scope.page``` model to be easily saved.

Maybe also consider resolving external CSS, JS, etc.?

**Comment by ethack** [comment]
If you don't end up mirroring the external resources (CSS, JS, images, etc) then the HTML `<base>` tag is very useful.  You can just insert that tag at the beginning of the `<head>` with the URL that the site was originally hosted at and all of the relative URLs elsewhere will magically still work despite the page being hosted on another domain.

**Comment by jordan-wright** [comment]
Using a ```<base>``` tag is a great idea! I've been considering whether or not to mirror external resources. There's pros and cons:

**Pros**

* More reliable and consistent page layout - if the site changes, the phishing site won't
* Removes trackers - this is really only important for pentesting engagements. Business training shouldn't care too much
* Quicker load times

**Cons**

* Need to implement XML parsing to find dependencies
* Need to create code to pull those down
* and change their links to be relative to the root
* and store them somewhere on the filesystem

I might do ```0.1``` using the ```<base>``` tag, but have a greyed out checkbox to "host external files locally" or "full mirror" or something like that.

Thanks for the suggestion!

**Comment by jordan-wright** [comment]
Now that I think about it, removing tracking should be fairly easy to do with basic html parsing. Something like looking for any 1x1 image and removing it should work in most cases.

**Comment by jordan-wright** [comment]
Closed via fad36607e443c4209fb2e424bf55eecfeb86c2d7 - importing a site now works as expected!
