### ISSUE TITLE
Phishing server use 80 port may need root

### ISSUE THREAD

**Issue by harrifeng** [jordan-wright/gophish#46]
I tried go run gophish.go, and it's always closing immediately.

I found it might because the 80 port need root, however root may have different GOPATH.

**Comment by jordan-wright** [comment]
Hey @harrifeng, you can try to change this line in ```config.json```:
```
	"phish_url" : "0.0.0.0:80",
```

If you change that to something other than 80, that should fix your problem. I apologize for not having this documented. I know it looks like there hasn't been repo updates in a few days, but I've been working offline on better documentation in general. :smile: 

Let me know if this fixes the issue! If not, I'll be happy to help any way I can.

**Comment by harrifeng** [comment]
Hi @jordan-wright issue is fixed, thanks for your help!
